version: "3"

services:
  yt-dlp-web:
    image: sooros5132/yt-dlp-web
    container_name: yt-dlp-web
    user: 1000:1000
    # environment:
    #   NEXT_PUBLIC_APP_NAME: yt-dlp-app
    #   NEXT_PUBLIC_APP_DESCRIPTION: yt-dlp-app
    #   NEXT_PUBLIC_APP_GENERATOR: yt-dlp-app
    #   If you need to protect the site, set AUTH_SECRET, CREDENTIAL_USERNAME, CREDENTIAL_PASSWORD.
    #   AUTH_SECRET: "Random_string,_40+_characters_recommended"
    #   CREDENTIAL_USERNAME: "username"
    #   CREDENTIAL_PASSWORD: "password"

    env_file:
      - .env
    volumes:
      - ~/Desktop/downloads:/downloads
      - ~/Desktop/cache:/cache
    ports:
      - 3000:3000
    restart: unless-stopped
