version: "3"

services:
  grab-video-web:
    image: mabsimon/grabvideo:latest
    container_name: grab-video
    user: 1000:1000
    # environment:
    #   If you need to protect the site, set AUTH_SECRET, CREDENTIAL_USERNAME, CREDENTIAL_PASSWORD.
    #   AUTH_SECRET: "Random_string,_40+_characters_recommended"
    #   CREDENTIAL_USERNAME: "username"
    #   CREDENTIAL_PASSWORD: "password"

    env_file:
      - .env
    volumes:
      - ~/Desktop/downloads:/downloads
      - ~/Desktop/cache:/cache
    ports:
      - 3000:3000
    restart: unless-stopped
